"""change duration type

Revision ID: 1e2384a4a01a
Revises: 91b73dda0776
Create Date: 2024-10-14 20:43:36.916175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2384a4a01a'
down_revision: Union[str, None] = '91b73dda0776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kpi', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kpi', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
