"""Add id to kpi

Revision ID: 6aa2891e7214
Revises: d01f0bbfb17e
Create Date: 2024-10-12 21:03:02.438254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa2891e7214'
down_revision: Union[str, None] = 'd01f0bbfb17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'id')
    # ### end Alembic commands ###
