"""added users and roles

Revision ID: caf7a0fe6323
Revises: 1e2384a4a01a
Create Date: 2024-11-03 10:51:00.517399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf7a0fe6323'
down_revision: Union[str, None] = '1e2384a4a01a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('kpi', 'url',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('kpi', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('kpi', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('fki_pageskpi', table_name='kpi')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('fki_pageskpi', 'kpi', ['page_id'], unique=False)
    op.alter_column('kpi', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('kpi', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('kpi', 'url',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
